clc;
close all;
fc = 20;         
fm = 5;       
fs = 100 * fc;      
t = 0:1/fs:4/fm;  
mt = sin(2*pi*fm*t);
ct = sawtooth(2*pi*fc*t);
pwm = mt > ct;
i_pwm = ~pwm;
edge_trigger = [0, diff(i_pwm) > 0];
ppm = zeros(size(t)); 
ppm(find(edge_trigger)) = i_pwm(find(edge_trigger));
figure;
subplot(6,1,1);
plot(t, mt);
title('Message Signal (Sine Wave)');
xlabel('Time (s)');
ylabel('Amplitude');
subplot(6,1,2);
plot(t, ct);
title('Carrier Signal (Sawtooth Wave)');
xlabel('Time (s)');
ylabel('Amplitude');
subplot(6,1,3);
plot(t, pwm);
title('PWM Signal');
xlabel('Time (s)');
ylabel('Amplitude');
subplot(6,1,4);
plot(t, i_pwm);
title('Inverted PWM Signal');
xlabel('Time (s)');
ylabel('Amplitude');
subplot(6,1,5);
stem(t, edge_trigger);
title('Positive Edge-Triggered Pulses');
xlabel('Time (s)');
ylabel('Amplitude');
subplot(6,1,6);
plot(t, ppm);
title('PPM Signal');
xlabel('Time (s)');
ylabel('Amplitude');
